version: '2'
services:
    cloudbaboons-app:
        image: cloudbaboons
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cloudbaboons-mysql:3306/cloudbaboons?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8089:8089
    cloudbaboons-mysql:
        extends:
            file: mysql.yml
            service: cloudbaboons-mysql
